spring.application.name=companymsApplication

server.port=8081

# #MySql
# spring.datasource.url=jdbc:mysql://localhost:3306/companymsappdb
# spring.datasource.username=root
# spring.datasource.password=${PASSWORD}
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# Postgresql
spring.datasource.url=jdbc:postgresql://localhost:3306/companymsappdb
spring.datasource.username=jobdb
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=POSTGRESQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Zipkin
management.tracing.sampling.probability=1.0
#management.zipkin.tracing.endpoint=

#RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest